Propse var reorganisation
AAROC/discourse-sso pull request #16
Opened 2019-05-03 17:03 UTC by gwarf

Move vars from `vars/main.yml` to `defaults/main.yml` so that all the variables can easily be overridden when including the role in another playbook.
Related to #14

2019-05-06 12:37 UTC, brucellino requested changes

2019-05-06 12:37 UTC, brucellino commented on README.md
> +Variables are used to tune the Rails application that runs Discourse. These are in a template, and set in the `defaults/main.yml` file. Please read them and set them accordingly in your playbook
Following our discussion in #14 I suggest we keep the original text, but remove `vars/main.yml` from change control.

2019-05-06 12:37 UTC, brucellino commented on defaults/main.yml
> +# discourse_hostname:
These are sane defaults, so I think they can stay.

2019-05-06 12:37 UTC, brucellino commented on defaults/main.yml
> +developer_emails: 'brucellino@gmail.com'
This is not a sane default though

2019-05-06 12:37 UTC, brucellino commented on defaults/main.yml
> +smtp_username: postmaster@sandbox6c9929c31d284bdba0a154af210f7130.mailgun.org
neither is this.

2019-05-06 12:37 UTC, brucellino commented on defaults/main.yml
> +discourse_plugins:
It doesn't make sense to have a long list of default plugins, every discourse is special :snowflake: but perhaps these are good examples of defaults. I'm ok with the list.

2019-05-06 12:47 UTC, gwarf commented
So was I was unsure I proposed to move all the contents from `vars/main.yml` to `defaults/main.yml`, but once the plan will be OK I will clean and use only the sane default values you mentioned. I was just confused by this embedding of non-easily overridable deployment-specific conf in the role.

2019-05-06 15:34 UTC, brucellino approved these changes
With a minor tweak of the README, I am staisfied

2019-06-18 10:42 UTC, gwarf commented
I've updated some of the defaults, let me know if it's OK with you and please squash/merge.
This should also close #14.

2019-06-18 10:56 UTC, brucellino approved these changes
The defaults make sense, so I'm ok with having the vars there.

2019-06-18 10:57 UTC, merged